# Generated by Django 5.1.7 on 2025-03-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MySQLSalesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=100)),
                ('sale_date', models.DateField()),
                ('sales_rep', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('sales_amount', models.FloatField()),
                ('quantity_sold', models.IntegerField()),
                ('product_category', models.CharField(max_length=100)),
                ('unit_cost', models.FloatField()),
                ('unit_price', models.FloatField()),
                ('customer_type', models.CharField(max_length=100)),
                ('discount', models.FloatField()),
                ('payment_method', models.CharField(max_length=50)),
                ('sales_channel', models.CharField(max_length=50)),
                ('region_and_sales_rep', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'mysql_salesdata',
            },
        ),
        migrations.CreateModel(
            name='PostgresSalesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=100)),
                ('sale_date', models.DateField()),
                ('sales_rep', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('sales_amount', models.FloatField()),
                ('quantity_sold', models.IntegerField()),
                ('product_category', models.CharField(max_length=100)),
                ('unit_cost', models.FloatField()),
                ('unit_price', models.FloatField()),
                ('customer_type', models.CharField(max_length=100)),
                ('discount', models.FloatField()),
                ('payment_method', models.CharField(max_length=50)),
                ('sales_channel', models.CharField(max_length=50)),
                ('region_and_sales_rep', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'postgres_salesdata',
            },
        ),
        migrations.CreateModel(
            name='SalesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=100)),
                ('sale_date', models.DateField()),
                ('sales_rep', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('sales_amount', models.FloatField()),
                ('quantity_sold', models.IntegerField()),
                ('product_category', models.CharField(max_length=100)),
                ('unit_cost', models.FloatField()),
                ('unit_price', models.FloatField()),
                ('customer_type', models.CharField(max_length=100)),
                ('discount', models.FloatField()),
                ('payment_method', models.CharField(max_length=50)),
                ('sales_channel', models.CharField(max_length=50)),
                ('region_and_sales_rep', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'sales_data_sqlite_fixed',
            },
        ),
    ]
